README.rst
blog/models.py
blog/templates/blog/list.html
blog/templates/blog/page.html
blog/views.py
requirements.txt
tests/test_settings.py
tests/tests_views.py

Create reusable breadcrumbs with microdata

[ 706 ] seo app + Crumbs

---

pages/migrations/0014_auto_20170504_0944.py
pages/models.py

Удалил создание базового шаблона, как обсуждали.

Page templates update

---

generic_admin/sites.py
generic_admin/templates/admin/base.html
setup.py

Необходимо для реализации автокомплита в первой подзадаче #79

Add django-select2 package

---

generic_admin/front/js/components/plugins.es6

Implemented shortcut support for save and continue button

---

generic_admin/front/js/components/tableEditor/colModel.es6

Reverts fidals/refarm-site#105

Revert "fix table editors col label"

---

catalog/models.py
pages/models.py

Добавление метода, задача #140

Добавление метода get_active

---

ecommerce/mailer.py
tests/ecommerce/tests_mailer.py
tests/test_settings.py

Замена SHOP_EMAIL и EMAIL_RECEPIENT на EMAIL_RECEPIENTS

Замена переменных на EMAIL_RECEPIENTS

---

LICENSE
ecommerce/front/paths.js
ecommerce/front/tracker.es6
ecommerce/front/trackers.es6

#292 ecommerce analytics

---

.editorconfig

rf#112  Add .editorconfig

---

pages/models.py
pages/utils.py
pages/views.py
tests/pages/test_views.py
tests/pages/urls.py
tests/test_settings.py

Related to fidals/shopelectro#343

Create and test RobotsView

---

ecommerce/front/trackers.es6

#147 Remove object spread from js

---

setup.py

Pin celery

---

catalog/models.py

https://github.com/fidals/shopelectro/issues/481
Closes #161

se#481 #161  Create method `get_category_descendants`

---

catalog/models.py

https://github.com/fidals/shopelectro/issues/547

se#547  Move some products filter logic from SE to catalog QuerySet

---

ecommerce/tasks.py

se#561 Create logging for send_mail task. Set acks_late=True.

---

catalog/models.py

Move TagQS.as_string to refarm
Add ProductQS.active() method

rf#168  Custom QuerySet minor fixes

---

.travis.yml
docker/Dockerfile.python
setup.py

se#570 Migrate python to 3.7

---

catalog/context.py

https://github.com/fidals/shopelectro/issues/577
Refarm requires some tests for context module.
But tests are waiting for this module refacroting at https://github.com/fidals/shopelectro/issues/567

se#577  Move context module to refarm.catalog app

---

catalog/models.py
pages/models.py

#169  Rm get_active method

---

catalog/models.py

#fix  Rm missed actives method call

---

refarm_pagination/pagination.py
tests/refarm_pagination/test_pagination.py

#175 test pagination

---

catalog/models.py

rf#182  Inherit CategoryManager from TreeManager

---

catalog/context.py

rf#182  Fix ProductImage context inheritance processing

---

catalog/context.py

https://github.com/fidals/shopelectro/issues/603

se#603  Fix long serv response

---

catalog/context.py

Closes https://github.com/fidals/stroyprombeton/issues/325
https://github.com/fidals/shopelectro/issues/603

stb#325  Fix performance issues for category and sorting

---

catalog/context.py

#197, #198  Rm prepare_data context

---

pages/templatetags/pages_extras.py

https://github.com/fidals/shopelectro/issues/629

se#629  Patch because of wrong query manager inheritance error

---

catalog/models.py

Remove `ordering` arguments from get_by_category 

---

catalog/helpers.py
catalog/urls.py

https://github.com/fidals/stroyprombeton/issues/344

stb#344  Create helper for se and stb category tests

---

catalog/views/catalog.py

https://github.com/fidals/shopelectro/issues/642

se#642  Fix CBV for se's no-images link

---

catalog/models.py
pages/models.py

#199  Fix model inheritance problem

---

catalog/models.py

https://github.com/fidals/stroyprombeton/issues/374

stb#374  Let group_tag_pairs return sorted tags list

---

catalog/models.py

https://github.com/fidals/stroyprombeton/issues/381

stb#381  Fix tags sorting error

---

images/models.py

Closes https://github.com/fidals/stroyprombeton/issues/296

stb#296  Subtask media-fixtures inconsistency fixing

---

ecommerce/views.py
pages/models.py
tests/ecommerce/tests_views.py
tests/ecommerce/urls.py
tests/test_settings.py

Closes https://github.com/fidals/shopelectro/issues/619

se#669  Create order test

---

refarm_test_utils/runners.py

Closes fidals/stroyprombeton#377

stb#377 Add predicate in the check_tagged_tests to identify a failed test.

---

docker/.env.dist
ecommerce/views.py
pages/models.py
pages/templatetags/pages_extras.py
pages/urls.py
search/views.py
tests/catalog/urls.py
tests/ecommerce/tests_views.py
tests/ecommerce/urls.py
tests/management/commands/create_fixtures.py
tests/pages/test_views.py
tests/search/urls.py
tests/test_settings.py

Closes #228
Closes #229
Closes #230

Set of order test improves

---

setup.py

Related to fidals/shopelectro#685 and fidals/stroyprombeton#393

Bump django version

---

setup.py

Required for https://github.com/fidals/stroyprombeton/issues/309

#fix  Grade sorl thumbnail to latest version

---

catalog/newcontext/context.py
catalog/newcontext/products.py
images/models.py

#246 Create ImageQeurySet

---

docker/docker-compose.yml
ecommerce/models.py
tests/ecommerce/tests_views.py
tests/ecommerce/urls.py

Closes https://github.com/fidals/shopelectro/issues/678

se#678  Test double order placing

---

refarm_pagination/context.py

Related to fidals/shopelectro#701

se#701 Add total_products to pagination context.

---

pages/utils.py
setup.py

Related to fidals/shopelectro#651 and maybe applicable to fidals/stroyprombeton#403

se#651 Remove the template rendering approach of segfault  

---

catalog/context.py
catalog/models.py
catalog/newcontext/products.py
tests/catalog/test_models.py

#253  Cleanup ProductsQuerySet

---

generic_admin/views.py

Add handler for a product without related models (options, category, page, ...)
Related to fidals/stroyprombeton#424

stb#424 Handle a product without related model.

---

.travis.yml
docker/docker-compose.yml

Rename for commands history compatibility with sites

#fix  Rename docker service to "app"

---

setup.py

#264 Bump django

---

.travis.yml
catalog/models.py
catalog/newcontext/context.py
catalog/newcontext/products.py
catalog/typing.py
docker/docker-compose.yml
refarm_pagination/context.py
tests/catalog/test_context.py

#255  Move products context to the QS

---

pages/models.py
pages/urls.py
tests/pages/urls.py

Merge it immediately. Minor fix is required for https://github.com/fidals/shopelectro/pull/726

#fix  Index page url reverse

---

catalog/newcontext/products.py
pages/display.py
pages/models.py
tests/pages/test_display.py
tests/pages/test_models.py

https://github.com/fidals/shopelectro/issues/728

se#728  Adapt interface of display module to actual site

---

catalog/models.py

#275 Drop _make_slug_unique

---

ecommerce/views.py

#279 Remove wrong todo task

---

tests/pages/test_models.py

Closes https://github.com/fidals/shopelectro/issues/742

se#742  Create test for descriptor issue

---

pages/display.py
tests/pages/test_models.py

#287  Use global context for display organization

---

catalog/models.py

https://github.com/fidals/shopelectro/issues/747

se#747  Sort tag-group pairs by group names

---

catalog/context.py
catalog/models.py
catalog/newcontext/tags.py
tests/catalog/test_models.py

#282 #291 use alphanumeric tag ordering

---

catalog/models.py
catalog/models_operations.py
tests/catalog/test_models.py

#296 preserve tag's whitespaces for alpanumeric ordering index

---

pages/display.py
tests/pages/test_display.py

#295 Implement __set_name__ for display.Page

---

.travis.yml
catalog/context.py
catalog/models.py
catalog/newcontext/tags.py
docker/docker-compose.yml
setup.py
tests/catalog/test_models.py
tests/test_settings.py

Closes #294 
Closes #235
Closes #142

#fixes  Bunch of minor fixes

---

pages/display.py
tests/pages/test_display.py
tests/pages/test_models.py

#267  Improve test_display tests

---

catalog/context/__init__.py

#fix  catalog.context structure issue

---

pages/utils.py

#268  Drop not actual task

---

catalog/models.py
pages/utils.py
tests/catalog/models.py
tests/ecommerce/models.py

Create Position class
Closes #261

#261  Document catalog terms with classes Arch

---

catalog/models.py

https://github.com/fidals/shopelectro/issues/805

se#805  Drop price field from admin

---

ecommerce/front/trackers.es6

#320 Use google analytics command queue

---

generic_admin/filters.py

Related to fidals/stroyprombeton#592

stb#592 Make a model lookup configurable for PriceRange admin filter

---

catalog/views/catalog.py
pages/models.py
pages/templatetags/pages_extras.py

https://github.com/fidals/shopelectro/issues/820

se#820  Show only active on the matrix page

---

pages/templates/pages/breadcrumbs.html
pages/templatetags/pages_extras.py

https://github.com/fidals/stroyprombeton/issues/641

stb#641  Use absolute path to breadcrumbs url items

---

pages/templatetags/pages_extras.py

https://github.com/fidals/shopelectro/issues/838
minor fix for breadcrumbs templates tag

se#838  Fix crumbs list

---

generic_admin/models.py

Related to fidals/shopelectro#835 and https://github.com/fidals/stroyprombeton/issues/613

se#835 Remove price field from AdminProductPage

---

generic_admin/front/js/components/plugins.es6

Related fidals/stroyprombeton#640

stb#640 Add pageTypes argument to constructor

---

arch_draft.py
pages/context/base.py
search/arch_draft.py

#331  Proposition for a new search app arch

---

generic_admin/mixins.py

Related to https://github.com/fidals/shopelectro/issues/868

Handle cases for occupied redirect entities in AutoCreateRedirect.

---

refarm_test_utils/runners.py

Related to fidals/stroyprombeton#505

stb#505 Implement a failed test rerun feature

---

pages/logic/__init__.py
pages/logic/page.py
pages/templatetags/pages_extras.py
tests/pages/logic/test_page.py

Closes #343 
- Drop redundant logic from siblings fetching
- High level arch for breadcrumbs

#343  Fix siblings logic. Refactor Breadcrumbs arch

---

catalog/context/category.py
catalog/models.py

https://github.com/fidals/shopelectro/issues/971

se#971 Seo fixes 25.09.19
